{% set version = "1.5" %}
{% set plugins_rev = "201712" %}
{% set sha256 = "a02b515ea51d86352b089c63d778fb5e8b9d784937cf157e587189cb97ad922d" %}

package:
  name: htslib
  version: "{{ version }}"

about:
  home: https://github.com/samtools/htslib
  license: MIT
  summary: C library for high-throughput sequencing data formats.

build:
  number: 0
  string: plugins_{{ plugins_rev }}_{{ PKG_BUILDNUM }}
  
source:
  - url: https://github.com/samtools/htslib/releases/download/{{ version }}/htslib-{{ version }}.tar.bz2
    fn: htslib-{{ version }}.tar.bz2
    sha256: {{ sha256 }}
  - git_url: https://github.com/samtools/htslib-plugins.git
    git_rev: {{ plugins_rev }}
    folder: plugins

features:
  - irods

requirements:
  build:
    - bzip2 # provides libbz2
    - curl
    - xz    # provides liblzma
    - zlib
