{% set version = "v1.2.0" %}

package:
  name: freebayes
  version: "{{ version }}"

about:
  home: https://github.com/ekg/freebayes
  license: MIT
  summary: Bayesian haplotype-based genetic polymorphism discovery and genotyping.

build:
  number: 0

source:
  git_url: https://github.com/ekg/freebayes.git
  git_tag: {{ version }}
  patches:
    - src/Makefile.patch
    - vcflib/tabixpp/Makefile.patch

requirements:
  build:
    - libbzip2
    - libcurl
    - gcc_npg >=7.3
    - liblzma
    - openssl
    - zlib

  run:
    - libbzip2
    - libcurl
    - gcc_npg >=7.3
    - libgcc_npg >=7.3
    - liblzma
    - openssl
    - zlib

test:
  commands:
    - freebayes --help
