{% set version = "0.4.15" %}
{% set sha256 = "6d730389249ab1e34ffb0a3c5beaa44e116687ffa081e0176dab6c59ff271593" %}

package:
  name: python-magic
  version: "{{ version }}"

about:
  home: https://github.com/ahupp/python-magic
  license: MIT
  summary: "A python wrapper for libmagic."

build:
  number: 0

source:
  url: https://github.com/ahupp/python-magic/archive/{{ version }}.tar.gz
  fn: python-magic-{{ version }}.tar.gz
  sha256: {{ sha256 }}

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - magic
