{% set version = "8.41" %}
{% set sha256 = "244838e1f1d14f7e2fa7681b857b3a8566b74215f28133f14a8f5e59241b682c" %}

package:
  name: pcre
  version: "{{ version }}"

about:
  home: http://www.pcre.org/
  license: BSD
  summary: "Perl Compatible Regular Expressions."

build:
  number: 1
  
source:
  url: https://ftp.pcre.org/pub/pcre/pcre-{{ version }}.tar.gz
  fn: pcre-{{ version }}.tar.gz
  sha256: {{ sha256 }}

requirements:
  build:
    - libbzip2
    - gcc_npg >=7.3
    - zlib
    - xz

  run:
    - libbzip2
    - libgcc_npg >=7.3
    - zlib
    - xz

test:
  commands:
    - test -f ${PREFIX}/include/pcre.h
    - test -f ${PREFIX}/lib/libpcre.a
    - test -h ${PREFIX}/lib/libpcre.so
