{% set version = "10.28" %}
{% set samtools_version = "0.1.19" %}
{% set samtools_sha256 = "d080c9d356e5f0ad334007e4461cbcee3c4ca97b8a7a5a48c44883cf9dee63d4" %}

package:
  name: pb_calibration
  version: "{{ version }}"

about:
  home: https://github.com/wtsi-npg/pb_calibration
  license: GPLv3
  summary: "Filter and calibration programs for Illumina sequencing data (in BAM files)."

build:
  number: 0

source:
  - url: https://sourceforge.net/projects/samtools/files/samtools/{{ samtools_version }}/samtools-{{ samtools_version }}.tar.bz2/download
    fn: samtools-{{ samtools_version }}.tar.bz2
    folder: samtools
    sha256: {{ samtools_sha256 }}

  - git_url: https://github.com/wtsi-npg/pb_calibration
    git_rev: v{{ version }}
    folder: pb_calibration

requirements:
  build:
    - libcurl
    - gcc_npg >=7.3
    - libgd
    - staden_io_lib <=1.14.6
    - zlib

  run:
    - libcurl
    - libgd
    - staden_io_lib
    - zlib

test:
  commands:
    - ${PREFIX}/bin/calibration_pu
    - ${PREFIX}/bin/predictor_pu
