{% set cpan_version = "2.000024" %}
{% set canon_version = "2.24" %}
{% set sha256 = "2e9b917bd48a0615e42633b2a327494e04610d8f710765b9493d306cead98a05" %}

package:
  name: perl-local-lib
  version: "{{ canon_version }}"

about:
  home: https://github.com/Perl-Toolchain-Gang/local-lib
  license: Perl Artistic License
  summary: Create and use a local lib/ for perl modules with PERL5LIB.

build:
  number: 0
  
source:
  url: https://cpan.metacpan.org/authors/id/H/HA/HAARG/local-lib-{{ cpan_version }}.tar.gz
  fn: local-lib-{{ cpan_version }}.tar.gz
  sha256: {{ sha256 }}
