{% set version = "1.9+37_g5708485" %}
{% set htslib_version = "1.9+47_gc93b673" %}

package:
  name: samtools
  version: "{{ version }}"

about:
  home: https://github.com/samtools/samtools
  license: MIT
  summary: C library for high-throughput sequencing data formats.

build:
  number: 1

source:
  git_url: https://github.com/samtools/samtools.git
  git_rev: 5708485f861c096d50471a70bb996561a0514181

requirements:
  build:
    - {{ compiler("c") }}
    - autoconf
    - automake
    - make
    - perl
  host:
    - libhts-dev =={{ htslib_version }}
    - libz-dev
  run:
    - libhts
    - libz

outputs:
  - name: samtools-bin
    version: {{ version }}
    requirements:
      build:
        - {{ compiler("c") }}
        - autoconf
        - automake
        - make
        - perl
      host:
        - libhts-dev =={{ htslib_version }}
        - libz-dev
      run:
        - libhts
        - libz
    files:
      - bin/ace2sam
      - bin/maq2sam-*
      - bin/md5*
      - bin/plot-bamstats
      - bin/samtools
      - bin/wgsim
      - bin/*.pl
      - bin/*.py
    test:
      commands:
        - echo '@HD VN:1.0 SO:coordinate' | samtools view

  - name: samtools-dev
    version: {{ version }}
    requirements:
      run:
        - libhts =={{ htslib_version }}
        - libz
    files:
      - include/samtools/*.h
      - lib/libbam.a
