{% set version = "1.7043" %}
{% set sha256 = "68a06f7da80882a95bc02c92c7ee305846fb6ab648cf83678ea945e44ad65c65" %}

package:
  name: perl-app-cpanminus
  version: "{{ version }}"

about:
  home: https://github.com/miyagawa/cpanminus
  license: Perl Artistic License
  summary: "Get, unpack, build and install modules from CPAN."

build:
  number: 1
  
source:
  url: https://cpan.metacpan.org/authors/id/M/MI/MIYAGAWA/App-cpanminus-{{ version }}.tar.gz
  fn: App-cpanminus-{{ version }}.tar.gz
  sha256: {{ sha256 }}

requirements:
  build:
    - perl ==5.22.2

  run:
    - perl ==5.22.2
