{% set version = "1.2.2" %}
{% set sha256 = "b09a5b871e1b7b8babb69b96609e7ac28db33c1a2b6febe6eb3b8a5dc1e41f44" %}

package:
    name: ivar
    version: "{{ version }}"

about:
    home: https://andersen-lab.github.io/ivar/html/
    license: GPL-3.0
    summary: iVar is a computational package that contains functions broadly useful
        for viral amplicon-based sequencing.

source:
    sha256: {{ sha256 }}
    url: https://github.com/andersen-lab/ivar/archive/v{{ version }}.tar.gz

build:
    number: 0

requirements:
    build:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 0_gnu
        - autoconf 2.69 pl526h14c3975_9
        - automake 1.16.2 pl526_0
        - binutils_impl_linux-64 2.34 h53a641e_5
        - binutils_linux-64 2.34 hc952b39_20
        - gcc_impl_linux-64 7.5.0 hd420e75_6
        - gcc_linux-64 7.5.0 h09487f9_20
        - gxx_impl_linux-64 7.5.0 hdf63c60_6
        - gxx_linux-64 7.5.0 h09487f9_20
        - ld_impl_linux-64 2.34 h53a641e_5
        - libgcc-ng 9.2.0 h24d8f2e_2
        - libgomp 9.2.0 h24d8f2e_2
        - libstdcxx-ng 9.2.0 hdf63c60_2
        - libtool 2.4.6 h14c3975_1002
        - m4 1.4.18 h14c3975_1001
        - make 4.3 h516909a_0
        - perl 5.26.2 h516909a_1006
        - pkg-config 0.29.2 h516909a_1006
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 0_gnu
        - bzip2 1.0.8 h516909a_2
        - ca-certificates 2020.6.20 hecda079_0
        - curl 7.71.1 he644dc0_0
        - htslib 1.10.2 hd3b49d5_1
        - krb5 1.17.1 hfafb76e_1
        - libcurl 7.71.1 hcdd3856_0
        - libdeflate 1.6 h516909a_0
        - libedit 3.1.20191231 h46ee950_0
        - libgcc-ng 9.2.0 h24d8f2e_2
        - libgomp 9.2.0 h24d8f2e_2
        - libssh2 1.9.0 hab1572f_2
        - libstdcxx-ng 9.2.0 hdf63c60_2
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1g h516909a_0
        - tk 8.6.10 hed695b0_0
        - xz 5.2.5 h516909a_0
        - zlib 1.2.11 h516909a_1006
    run:
        - bzip2 >=1.0.8,<2.0a0
        - bzip2 >=1.0.8,<2.0a0
        - curl >=7.71.1,<8.0a0
        - htslib >=1.10.2,<1.11.0a0
        - htslib >=1.10.2,<1.11.0a0
        - libdeflate >=1.6,<1.7.0a0
        - libgcc-ng >=7.5.0
        - libstdcxx-ng >=7.5.0
        - xz >=5.2.5,<5.3.0a0
        - xz >=5.2.5,<5.3.0a0
        - zlib >=1.2.11,<1.3.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - ivar version
