{% set version = "4.6.4" %}
{% set sha256 = "53de33db01815914b3905a7d2cefac1ecf24ad081b82d93e4f526d8e62ff736f" %}

{% set gmp_version = "4.3.2" %}
{% set gmp_sha256 = "936162c0312886c21581002b79932829aa048cfaf9937c6265aeaa14f1cd1775" %}

{% set mpfr_version = "2.4.2" %}
{% set mpfr_sha256 = "c7e75a08a8d49d2082e4caee1591a05d11b9d5627514e678f02d66a124bcf2ba" %}

{% set mpc_version = "0.8.1" %}
{% set mpc_sha256 = "e664603757251fd8a352848276497a4c79b7f8b21fd8aedd5cc0598a38fee3e4" %}

package:
  name: gcc_npg
  version: "{{ version }}"

about:
  home: https://gcc.gnu.org/
  license: GPLv3
  summary: The GNU Compiler Collection.

build:
  number: 1

  rpaths:
    - lib64
    - lib

source:
  - url: ftp://ftp.mirrorservice.org/sites/sourceware.org/pub/gcc/releases/gcc-{{ version }}/gcc-{{ version }}.tar.gz
    fn: gcc-{{ version }}.tar.gz
    folder: gcc-src
    sha256: {{ sha256 }}

  - url: https://gmplib.org/download/gmp/archive/gmp-{{ gmp_version }}.tar.bz2
    fn: gmp-{{ gmp_version }}.tar.bz2
    folder: gmp-src
    sha256: {{ gmp_sha256 }}

  - url: http://www.mpfr.org/mpfr-{{ mpfr_version }}/mpfr-{{ mpfr_version }}.tar.bz2
    fn: mpfr-{{ mpfr_version }}.tar.bz2
    folder: mpfr-src
    sha256: {{ mpfr_sha256 }}

  - url: http://www.multiprecision.org/downloads/mpc-{{ mpc_version }}.tar.gz
    fn: mpc-{{ mpc_version }}.tar.gz
    folder: mpc-src
    sha256: {{ mpc_sha256 }}

outputs:
  - name: gcc_npg
    version: {{ version }}
    requirements:
      run:
        - libgcc_npg =={{ version }}
    files:
      - bin/c++
      - bin/g++
      - bin/cpp
      - bin/gfortran
      - bin/gcc*
      - bin/gcov*
      - bin/x86_64*
      - include
      - lib
      - libexec
      - share

  - name: libgcc_npg
    version: {{ version }}
    files:
      - lib64
