{% set version = "1.6" %}
{% set plugins_rev = "201712" %}
{% set sha256 = "9588be8be0c2390a87b7952d644e7a88bead2991b3468371347965f2e0504ccb" %}

package:
  name: htslib
  version: "{{ version }}"

about:
  home: https://github.com/samtools/htslib
  license: MIT
  summary: C library for high-throughput sequencing data formats.

build:
  number: 1
  string: plugins_{{ plugins_rev }}_{{ PKG_BUILDNUM }}

source:
  - url: https://github.com/samtools/htslib/releases/download/{{ version }}/htslib-{{ version }}.tar.bz2
    fn: htslib-{{ version }}.tar.bz2
    sha256: {{ sha256 }}
  - git_url: https://github.com/samtools/htslib-plugins.git
    git_rev: {{ plugins_rev }}
    folder: plugins

features:
  - irods

requirements:
  build:
    - bzip2
    - libcurl
    - gcc_npg >=7.3
    - irods-dev # for plugins
    - xz
    - zlib

  run:
    - bzip2
    - libcurl
    - xz
    - zlib

test:
  commands:
    - test -f ${PREFIX}/include/htslib/sam.h
    - test -f ${PREFIX}/lib/libhts.a
    - test -h ${PREFIX}/lib/libhts.so
    - test -f ${PREFIX}/libexec/htslib/hfile_irods.so
    - test -f ${PREFIX}/libexec/htslib/hfile_libcurl.so
