{% set version = "1.2.4" %}

package:
  name: tears
  version: "{{ version }}"

about:
  home: https://github.com/whitwham/tears
  license: GPLv3
  summary:  Stream files to and from iRODS.

build:
  number: 0

source:
  git_url: https://github.com/whitwham/tears.git
  git_rev: v{{ version }}

features:
  - irods

requirements:
  build:
    - gcc_npg >=7.3
    - htslib >=1.7
    - irods-dev
    - jansson

  run:
    - htslib >=1.7
    - jansson

test:
  commands:
    - test -x ${PREFIX}/bin/tears
