{% set version = "1.3.0" %}
{% set sha256 = "65b41aaf18186124a7d11a0a33267e9d8e2b48ce2939193cf60e84297995158a" %}

package:
  name: valet
  version: "{{ version }}"

about:
  home: https://github.com/kjsanger/valet 
  license: GPL3
  summary: "valet is a utility for performing data management tasks automatically."

build:
  number: 0
  binary_relocation: false

source:
  url: https://github.com/kjsanger/valet/releases/download/v{{ version }}/valet-v{{ version }}.tar.bz2
  sha256: {{ sha256 }}

test:
  commands:
    - valet -h
