{% set version = "1.1.3" %}
{% set libstatgen_version = "1.0.14" %}

package:
  name: verifybamid
  version: "{{ version }}"

about:
  home: http://genome.sph.umich.edu
  license: Various
  summary: Verify identity and purity of sequence data.

source:
  - git_url: https://github.com/statgen/verifyBamID.git
    git_rev: v{{ version }}
    folder: verifybamid
  - git_url: https://github.com/statgen/libStatGen.git
    git_rev: v{{ libstatgen_version }}
    folder: libstatgen

requirements:
  build:
    - zlib
