{% set version = "0.4224" %}
{% set sha256 = "a6ca15d78244a7b50fdbf27f85c85f4035aa799ce7dd018a0d98b358ef7bc782" %}

package:
  name: perl-module-build
  version: "{{ version }}"

about:
  home: https://github.com/Perl-Toolchain-Gang/Module-Build
  license: Perl Artistic License
  summary: Build and install Perl modules.

build:
  number: 0
  
source:
  url: https://cpan.metacpan.org/authors/id/L/LE/LEONT/Module-Build-{{ version }}.tar.gz
  fn: Module-Build-{{ version }}.tar.gz
  sha256: {{ sha256 }}
