{% set version = "0.9.12" %}

package:
  name: bambi
  version: "{{ version }}"

about:
  home: https://github.com/wtsi-npg/bambi
  license: AGPL
  summary: A set of programs to manipulate SAM/BAM/CRAM files, using HTSLIB.

build:
  number: 0

source:
  git_url: https://github.com/wtsi-npg/bambi.git
  git_rev: {{ version }}

requirements:
  build:
    - htslib >=1.6
