{% set version = "0.8.5" %}

package:
  name: nanopolish
  version: "{{ version }}"

about:
  home: https://github.com/jts/nanopolish
  license: MIT
  summary: "Software package for signal-level analysis of Oxford Nanopore sequencing data."

build:
  number: 1

  rpaths:
    - lib64
    - lib

source:
  git_url: https://github.com/jts/nanopolish.git
  git_rev: v{{ version }}
  patches:
    - patch-build-system-htslib-gomp.patch

requirements:
  build:
    - libbzip2
    - eigen
    - gcc_npg >=7.3
    - hdf5
    - htslib >=1.7
    - liblzma
    - zlib

  run:
    - libbzip2
    - hdf5
    - htslib >=1.7
    - libgcc_npg >=7.3
    - liblzma
    - zlib
