{% set version = "64.5" %}
{% set htslib_version = "1.7" %}

{% set samtools_version = "1.7" %}
{% set samtools_sha256 = "e7b09673176aa32937abd80f95f432809e722f141b5342186dfef6a53df64ca1" %}

package:
  name: npg_qc_utils
  version: "{{ version }}"

about:
  home: https://github.com/keithj/npg_qc_utils
  license: GPLv3
  summary: "C programs extracted from npg_qc."

build:
  number: 0

source:
  - url: https://sourceforge.net/projects/samtools/files/samtools/{{ samtools_version }}/samtools-{{ samtools_version }}.tar.bz2/download
    fn: samtools-{{ samtools_version }}.tar.bz2
    folder: samtools
    sha256: {{ samtools_sha256 }}

  - git_url: https://github.com/keithj/npg_qc_utils.git
    git_rev: {{ version }}
    folder: npg_qc_utils

requirements:
  build:
    - gcc_npg >=7.3
    - htslib =={{ htslib_version }}
    - zlib

  run:
    - htslib =={{ htslib_version }}
    - zlib

test:
  commands:
    - ${PREFIX}/bin/fastq_summ -h
