{% set version = "1.6.3" %}
{% set sha256 = "8fdabcc0004216c3588b7dca0f23d104dfe012a47e2bb6f13827534a6ee73aa7" %}

package:
  name: apr
  version: "{{ version }}"

about:
  home: https://apr.apache.org/
  license: ASL
  summary: Apache Portable Runtime API.

build:
  number: 1

source:
  url: https://mirrors.ukfast.co.uk/sites/ftp.apache.org/apr/apr-{{ version }}.tar.gz
  fn: apr-{{ version }}.tar.gz
  sha256: {{ sha256 }}

requirements:
  build:
    - gcc_npg >=7.3
    - libuuid

  run:
    - libuuid

test:
  commands:
    - test -f ${PREFIX}/include/apr-1/apr.h
    - test -f ${PREFIX}/lib/libapr-1.a
    - test -h ${PREFIX}/lib/libapr-1.so.0
