{% set version = "1.6.3" %}
{% set sha256 = "8fdabcc0004216c3588b7dca0f23d104dfe012a47e2bb6f13827534a6ee73aa7" %}

package:
  name: apr
  version: "{{ version }}"

about:
  home: https://apr.apache.org/
  license: ASL
  summary: Apache Portable Runtime API.

source:
  url: https://mirrors.ukfast.co.uk/sites/ftp.apache.org/apr/apr-{{ version }}.tar.gz
  fn: apr-{{ version }}.tar.gz
  sha256: {{ sha256 }}

requirements:
  build:
    - gcc_linux-64 >=5.4
