{% set version = "1.47.0" %}
{% set alt_version = "1_47_0" %}
{% set sha256 = "815a5d9faac4dbd523fbcf3fe1065e443c0bbf43427c44aa423422c6ec4c2e31" %}

package:
  name: boost
  version: "{{ version }}"

about:
  home: http://www.boost.org
  license: Boost
  summary: "Free peer-reviewed portable C++ source libraries."

build:
  number: 0

  rpaths:
    - lib64
    - lib

source:
  url: https://sourceforge.net/projects/boost/files/boost/{{ version }}/boost_{{ alt_version }}.tar.bz2/download
  fn: boost_{{ alt_version }}.tar.bz2
  sha256: {{ sha256 }}

requirements:
  build:
    - bzip2
    - gcc_npg >=4.6,<5.0
    - xz
    - zlib

  run:
    - bzip2
    - libgcc_npg >=4.6,<5.0
    - xz
    - zlib

test:
  commands:
    - test -f ${PREFIX}/include/boost/config.hpp
    - test -f ${PREFIX}/lib/libboost_system.a
    - test -h ${PREFIX}/lib/libboost_system.so
