{% set version = "1.1.8" %}
{% set sha256 = "0a6a8cc885e77c7e7b75dafcfd2152e0d1031fa7aba2565250a46fbd98979793" %}

package:
  name: rna-seqc
  version: "{{ version }}"

about:
  home: https://software.broadinstitute.org/software/cprg/?q=node/38
  license: MIT
  summary: "RNA-SeQC is a java program which computes a series of quality control metrics for RNA-seq data."

build:
  number: 0
  
source:
  url: http://www.broadinstitute.org/cancer/cga/tools/rnaseqc/RNA-SeQC_v{{ version }}.jar
  fn: RNA-SeQC.jar
  sha256: {{ sha256 }}
