{% set version = "0.10.1" %}

package:
  name: bambi
  version: "{{ version }}"

about:
  home: https://github.com/wtsi-npg/bambi
  license: AGPL
  summary: A set of programs to manipulate SAM/BAM/CRAM files, using HTSLIB.

build:
  number: 0

source:
  git_url: https://github.com/wtsi-npg/bambi.git
  git_rev: devel

requirements:
  build:
    - gcc_npg >=7.3
    - htslib >=1.7
    - libgd
    - libxml2

  run:
    - htslib >=1.7
    - libgd
    - libxml2

test:
  commands:
    - bambi --version
