{% set version = "0.14.0" %}
{% set sha256 = "d5e432eb91becd51c94e78e3cb555b3cecd9fab7a4bfa3f932577e9b41444abf" %}

package:
  name: wr
  version: "{{ version }}"

about:
  home: https://github.com/VertebrateResequencing/wr
  license: GPLv3
  summary: "High performance Workflow Runner."

build:
  number: 0
  binary_relocation: false

source:
  url: https://github.com/VertebrateResequencing/wr/releases/download/v{{ version }}/wr-linux-x86-64.zip
  fn: wr-{{ version }}.zip
  sha256: {{ sha256 }}

test:
  commands:
    - wr -h
