{% set version = "1.8" %}
{% set sha256 = "4acbfd691f137742e0be63d09f516434f0faf617a5c60f466140e0677915fced" %}
{% set htslib_version = "1.9+66_gbcf9bff" %}

package:
  name: bcftools
  version: "{{ version }}"

about:
  home: https://github.com/samtools/samtools
  license: MIT
  summary: C library for high-throughput sequencing data formats.

build:
  number: 1

source:
  url: https://github.com/samtools/bcftools/releases/download/{{ version }}/bcftools-{{ version }}.tar.bz2
  fn: bcftools-{{ version }}.tar.bz2
  sha256: {{ sha256 }}

requirements:
  build:
    - gcc_npg >=7.3
    - htslib =={{ htslib_version }}

  run:
    - htslib =={{ htslib_version }}
