{% set version = "5.22.2" %}
{% set sha256 = "81ad196385aa168cb8bd785031850e808c583ed18a7901d33e02d4f70ada83c2" %}

package:
  name: perl
  version: "{{ version }}"

about:
  home: https://perl.org
  license: Perl Artistic License
  summary: The Perl Language.

build:
  number: 0
  
source:
  url: https://www.cpan.org/src/5.0/perl-{{ version }}.tar.gz
  fn: perl-{{ version }}.tar.gz
  sha256: {{ sha256 }}

requirements:
  build:
    - gcc_npg >=7.3

test:
  commands:
    - ${PREFIX}/bin/perl -v
