{% set version = "1.14.9" %}
{% set sha256 = "8d0732f3d37abba1633731bfacac5fd7f8172eccb1cef224e8ced904d3b242f4" %}

package:
  name: staden_io_lib
  version: "{{ version }}"

about:
  home: https://sourceforge.net/projects/staden
  license: BSD
  summary: DNA sequence assembly, editing and analysis tools.

build:
  number: 4

source:
  url: https://sourceforge.net/projects/staden/files/io_lib/{{ version }}/io_lib-{{ version }}.tar.gz/download
  fn: io_lib-{{ version }}.tar.gz
  sha256: {{ sha256 }}

requirements:
  build:
    - libbzip2
    - libcurl
    - gcc_npg >=7.3
    - liblzma
    - zlib

outputs:
  - name: staden_io_lib
    version: {{ version }}
    requirements:
      run:
        - libbzip2
        - libcurl
        - liblzma
        - zlib
    files:
      - bin/io_lib-config
      - lib/libstaden-read*
      - include/io_lib
      - share/man/man3/ExperimentFile.3
      - share/man/man3/exp2read.3
      - share/man/man3/fread_reading.3
      - share/man/man3/fread_scf.3
      - share/man/man3/fwrite_reading.3
      - share/man/man3/fwrite_scf.3
      - share/man/man3/read2exp.3
      - share/man/man3/read2scf.3
      - share/man/man3/read_allocate.3
      - share/man/man3/read_deallocate.3
      - share/man/man3/read_reading.3
      - share/man/man3/read_scf.3
      - share/man/man3/read_scf_header.3
      - share/man/man3/scf2read.3
      - share/man/man3/write_reading.3
      - share/man/man3/write_scf.3
      - share/man/man3/write_scf_header.3
      - share/man/man4/Read.4
    test:
      commands:
        - test -f ${PREFIX}/include/io_lib/io_lib_config.h
        - test -f ${PREFIX}/lib/libstaden-read.a
        - test -h ${PREFIX}/lib/libstaden-read.so
  - name: staden_io_bin
    version: {{ version }}
    requirements:
      run:
        - staden_io_lib =={{ version }}
        - libbzip2
        - libcurl
        - liblzma
        - zlib
    files:
      - bin/append_sff
      - bin/convert_trace
      - bin/cram_dump
      - bin/cram_filter
      - bin/cram_index
      - bin/cram_size
      - bin/extract_fastq
      - bin/extract_qual
      - bin/extract_seq
      - bin/get_comment
      - bin/hash_exp
      - bin/hash_extract
      - bin/hash_list
      - bin/hash_sff
      - bin/hash_tar
      - bin/index_tar
      - bin/makeSCF
      - bin/scf_dump
      - bin/scf_info
      - bin/scf_update
      - bin/scram_flagstat
      - bin/scram_merge
      - bin/scram_pileup
      - bin/scram_test
      - bin/scramble
      - bin/srf2fasta
      - bin/srf2fastq
      - bin/srf_dump_all
      - bin/srf_extract_hash
      - bin/srf_extract_linear
      - bin/srf_filter
      - bin/srf_index_hash
      - bin/srf_info
      - bin/srf_list
      - bin/trace_dump
      - bin/ztr_dump
      - share/man/man1/scramble.1
      - share/man/man1/srf2fasta.1
      - share/man/man1/srf2fastq.1
      - share/man/man1/srf_index_hash.1
      - share/man/man1/srf_info.1
      - share/man/man1/srf_list.1
    test:
      commands:
        - scramble -h
