
# Set -std=c++03 (see https://github.com/BenLangmead/bowtie/issues/76)
CXXFLAGS: "-march=x86-64 -mtune=generic -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -std=c++03"
