{% set version = "1.8" %}
{% set sha256 = "c942bc1d9b85fd1b05ea79c5afd2805d489cd36b2c2d8517462682a4d779be16" %}

package:
  name: samtools
  version: "{{ version }}"

about:
  home: https://github.com/samtools/samtools
  license: MIT
  summary: C library for high-throughput sequencing data formats.

build:
  number: 0

source:
  url: https://github.com/samtools/samtools/releases/download/{{ version }}/samtools-{{ version }}.tar.bz2
  fn: samtools-{{ version }}.tar.bz2
  sha256: {{ sha256 }}

requirements:
  build:
    - gcc_npg >=7.3
    - htslib =={{ version }}

  run:
    - htslib =={{ version }}

test:
  commands:
    - echo '@HD VN:1.0 SO:coordinate' | samtools view
