{% set version = "3.6" %}
{% set sha256 = "d24c0d0f2abffbc8f4f34dcf114b0f131ec3774895f3555922fe2f40f3d5e3f1" %}

package:
  name: nettle-pkg
  version: "{{ version }}"

about:
  home: https://www.lysator.liu.se/~nisse/nettle/
  license: GPL2
  summary: A low-level cryptographic library

build:
  number: 5

source:
  url: https://ftp.gnu.org/gnu/nettle/nettle-{{ version }}.tar.gz
  fn: nettle-{{ version }}.tar.gz
  sha256: {{ sha256 }}

requirements:
  build:
    - {{ compiler("c") }}
    - libtool
    - m4
    - make
    - pkg-config
  host:
    - libgmp-dev >=6.0
  run:
    - libgmp >=6.0

outputs:
  - name: nettle
    requirements:
      build:
        - {{ compiler("c") }}
        - libtool
        - m4
        - make
        - pkg-config
      host:
        - libgmp-dev >=6.0
      run:
        - {{ pin_subpackage("libnettle", exact=True) }}
        - libgmp >=6.0
    files:
      - bin/nettle-hash
      - bin/nettle-lfib-stream
      - bin/nettle-pbkdf2
      - bin/pkcs1-conv
      - bin/sexp-conv
    test:
      commands:
        - nettle-hash --help

  - name: libnettle
    version: {{ version }}
    requirements:
      build:
        - {{ compiler("c") }}
        - libtool
        - m4
        - make
        - pkg-config
      host:
        - libgmp-dev >=6.0
      run:
        - libgmp >=6.0
    files:
      - lib/libhogweed.*
      - lib/libnettle.*
    test:
      commands:
        - test -f ${PREFIX}/lib/libnettle.a
        - test -h ${PREFIX}/lib/libnettle.so
        - test -f ${PREFIX}/lib/libhogweed.a
        - test -h ${PREFIX}/lib/libhogweed.so

  - name: libnettle-dev
    version: {{ version }}
    requirements:
      run:
        - {{ pin_subpackage("libnettle", exact=True) }}
    files:
      - include/nettle
      - lib/pkgconfig/hogweed.pc
      - lib/pkgconfig/nettle.pc
    test:
      commands:
        - test -f ${PREFIX}/include/nettle/sha1.h
