{% set version = "2.32" %}
{% set sha256 = "ce43afee3182f1bddb0be83f68bd378770efb9b6fdd8f464333ff8e07903db56" %}

package:
  name: util-linux
  version: "{{ version }}"

about:
  home: https://mirrors.edge.kernel.org/pub/linux/utils/util-linux
  license: BSD
  summary: "Linux utilities from kernel.org"

build:
  number: 0

source:
  url: https://mirrors.edge.kernel.org/pub/linux/utils/util-linux/v{{ version }}/util-linux-{{ version }}.tar.gz
  fn: util-linux-{{ version }}.tar.gz
  sha256: {{ sha256 }}

outputs:
  - name: libuuid
    version: {{ version }}
    files:
      - include/uuid.h
      - lib/libuuid.a
      - lib/libuuid.so
      - lib/libuuid.so.1
      - lib/libuuid.so.1.3.0
      - share/man/man1/uuidgen.1
      - share/man/man3/uuid.3
      - share/man/man3/uuid_clear.3
      - share/man/man3/uuid_compare.3
      - share/man/man3/uuid_copy.3
      - share/man/man3/uuid_generate.3
      - share/man/man3/uuid_is_null.3
      - share/man/man3/uuid_parse.3
      - share/man/man3/uuid_time.3
      - share/man/man3/uuid_unparse.3

requirements:
  build:
    - gcc_npg >=7.3

test:
  commands:
    - test -f ${PREFIX}/include/uuid/uuid.h
    - test -f ${PREFIX}/lib/libuuid.a
    - test -h ${PREFIX}/lib/libuuid.so
