{% set version = "0.22.0" %}

package:
  name: p4
  version: "{{ version }}"

about:
  home: https://github.com/wtsi-npg/p4
  license: Unknown
  summary: "Process and Pipe Pipeline Panacea."

build:
  number: 0
  
source:
  git_url: https://github.com/wtsi-npg/p4.git
  git_rev: {{ version }}

test:
  commands:
    - test -x ${PREFIX}/bin/viv.pl
    - test -x ${PREFIX}/bin/vtfp.pl
