{% set version = "0.11.2" %}
{% set htslib_version = "1.9+66_gbcf9bff" %}


package:
  name: bambi
  version: "{{ version }}"

about:
  home: https://github.com/wtsi-npg/bambi
  license: AGPL
  summary: "A set of programs to manipulate SAM/BAM/CRAM files, using HTSLIB."

build:
  number: 0

source:
  git_url: https://github.com/wtsi-npg/bambi.git
  git_rev: 0.11.2

requirements:
  build:
    - gcc_npg >=7.3
    - htslib =={{ htslib_version }}
    - libgd
    - libxml2

  run:
    - htslib =={{ htslib_version }}
    - libgd
    - libxml2

test:
  commands:
    - bambi --version
