{% set version = "1.9+213_g706c7b4" %} # reset build to zero on changing
{% set htslib_version = "1.9+449_g9279d76" %}

package:
  name: samtools-pkg
  version: "{{ version }}"

about:
  home: https://github.com/samtools/samtools
  license: MIT
  summary: C library for high-throughput sequencing data formats.

build:
  number: 0

source:
  git_url: https://github.com/samtools/samtools.git
  git_rev: 706c7b4fb32e676e309810ef403a8aba63a5040a

requirements:
  build:
    - {{ compiler("c") }}
    - autoconf
    - automake
    - make
    - perl
  host:
    - libhts-dev =={{ htslib_version }}
    - libz-dev
  run:
    - libhts =={{ htslib_version }}
    - libz

outputs:
  - name: samtools
    version: {{ version }}
    requirements:
      build:
        - {{ compiler("c") }}
        - autoconf
        - automake
        - make
        - perl
      host:
        - libhts-dev =={{ htslib_version }}
        - libz-dev
      run:
        - libhts =={{ htslib_version }}
        - libz
    files:
      - bin/ace2sam
      - bin/maq2sam-*
      - bin/md5*
      - bin/plot-bamstats
      - bin/samtools
      - bin/wgsim
      - bin/*.pl
      - bin/*.py
    test:
      commands:
        - echo -e '@HD\tVN:1.0\tSO:unsorted' | samtools view

  - name: samtools-dev
    version: {{ version }}
    requirements:
      run:
        - libhts =={{ htslib_version }}
        - libz
    files:
      - include/samtools/*.h
      - lib/libbam.a
    test:
      commands:
        - test -f ${PREFIX}/include/samtools/sam.h
        - test -f ${PREFIX}/lib/libbam.a
