{% set version = "0.2.3" %}
{% set sha256 = "bfed39f82abc54f44fffd9b13d2121868084da7ac3d158ac9b9aa6fa0257f0f4" %}

package:
  name: porechop
  version: "{{ version }}"

about:
  home: https://github.com/rrwick/Porechop
  license: GPLv3
  summary: "Adapter trimmer for Oxford Nanopore reads."

build:
  number: 0

  rpaths:
    - lib64
    - lib
  
source:
  url: https://github.com/rrwick/Porechop/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

requirements:
  build:
    - gcc_npg >=5.5,<7.0.0
    - python >=3.4

  run:
    - python >=3.4
    - libgcc_npg >=5.5,<7.0.0

test:
  commands:
    - porechop --help
