{% set version = "1.0.2o" %}
{% set sha256 = "ec3f5c9714ba0fd45cb4e087301eb1336c317e0d20b575a125050470e8089e4d" %}

package:
  name: openssl
  version: "{{ version }}"

about:
  home: https://openssl.org/
  license: OpenSSL
  summary: "Cryptography and SSL/TLS Toolkit."

build:
  number: 1

source:
  - url: https://www.openssl.org/source/openssl-{{ version }}.tar.gz
    fn: openssl-{{ version }}.tar.gz
    sha256: {{ sha256 }}

outputs:
  - name: openssl
    version: {{ version }}
    requirements:
      build:
        - {{ compiler("c") }}
        - libtool
        - make
        - pkg-config
      host:
        - libz-dev
      run:
        - {{ pin_subpackage("libssl", exact=True) }}
        - libz
    files:
      - bin/c_rehash
      - bin/openssl
      - etc/ssl/man/man1
    test:
      commands:
        - openssl s_client -CApath /etc/ssl/certs/ -connect www.sanger.ac.uk:443

  - name: libssl
    version: {{ version }}
    requirements:
      build:
        - {{ compiler("c") }}
        - libtool
        - make
        - pkg-config
      host:
        - libz-dev
      run:
        - libz
    files:
      - lib/libcrypto.*
      - lib/libssl.*
      - lib/engines

  - name: libssl-dev
    version: {{ version }}
    requirements:
      run:
        - {{ pin_subpackage("libssl", exact=True) }}
    files:
      - etc/ssl/man/man3
      - include/openssl
