{% set version = "1.3.1" %}
{% set git_rev = "v1.3.1" %}

package:
  name: libpam
  version: "{{ version }}"

about:
  home: http://www.linux-pam.org/
  license: MIT
  summary: Linux PAM (Pluggable Authentication Modules for Linux) project

source:
  git_url: https://github.com/linux-pam/linux-pam.git
  git_rev: {{ git_rev }}

requirements:
  build:
    - {{ compiler("c") }}
    - autoconf
    - automake>=1.16.2
    - make
    - m4
    - libtool
    - pkg-config
  host:
    - gettext

outputs:
  - name: libpam
    files:
      - lib/libpam.so
      - lib/libpam.so.0
      - lib/libpam.so.0.84.2
      - lib/libpam.la
      - include/security/_pam_compat.h
      - include/security/_pam_macros.h
      - include/security/_pam_types.h
      - include/security/pam_appl.h
      - include/security/pam_ext.h
      - include/security/pam_modules.h
      - include/security/pam_modutil.h
