{% set version = "1.55.0" %}
{% set alt_version = "1_55_0" %}
{% set sha256 = "fff00023dd79486d444c8e29922f4072e1d451fc5a4d2b6075852ead7f2b7b52" %}

package:
  name: boost
  version: "{{ version }}"

about:
  home: http://www.boost.org
  license: Boost
  summary: "Free peer-reviewed portable C++ source libraries."

build:
  number: 1

  rpaths:
    - lib64
    - lib

source:
  url: https://sourceforge.net/projects/boost/files/boost/{{ version }}/boost_{{ alt_version }}.tar.bz2/download
  fn: boost_{{ alt_version }}.tar.bz2
  sha256: {{ sha256 }}

requirements:
  build:
    - libbzip2
    - gcc_npg >=4.6,<5.0
    - xz
    - zlib

  run:
    - libbzip2
    - libgcc_npg >=4.6,<5.0
    - xz
    - zlib

test:
  commands:
    - test -f ${PREFIX}/include/boost/config.hpp
    - test -f ${PREFIX}/lib/libboost_system.a
    - test -h ${PREFIX}/lib/libboost_system.so
