{% set version = "0.13.0" %}
{% set sha256 = "595e14148937c74e944f88f94c8cfad47c538e7718e754ab731e5405b5e015b0" %}

package:
  name: wr
  version: "{{ version }}"

about:
  home: https://github.com/VertebrateResequencing/wr
  license: GPLv3
  summary: "High performance Workflow Runner."

build:
  number: 0
  binary_relocation: false

source:
  url: https://github.com/VertebrateResequencing/wr/releases/download/v{{ version }}/wr-linux-x86-64.zip
  fn: wr-{{ version }}.zip
  sha256: {{ sha256 }}

test:
  commands:
    - wr -h
