{% set version = "2.10" %}
{% set sha256 = "b0a899f90ade82e42da0ecabc8af1fa296d69691e7c0786c4994fb79d4833ebb" %}

package:
  name: jansson
  version: "{{ version }}"

about:
  home: http://www.digip.org/jansson/
  license: MIT
  summary: C library for encoding, decoding and manipulating JSON data.

source:
  url: https://github.com/akheron/jansson/archive/v{{ version }}.tar.gz
  fn: jansson-{{ version }}.tar.gz
  sha256: {{ sha256 }}
