{% set version = "65.0" %}
{% set htslib_version = "1.8" %}

{% set samtools_version = "1.8" %}
{% set samtools_sha256 = "c942bc1d9b85fd1b05ea79c5afd2805d489cd36b2c2d8517462682a4d779be16" %}

package:
  name: npg_qc_utils
  version: "{{ version }}"

about:
  home: https://github.com/wtsi-npg/npg_qc_utils
  license: GPLv3
  summary: "C programs extracted from npg_qc."

build:
  number: 2

source:
  - url: https://sourceforge.net/projects/samtools/files/samtools/{{ samtools_version }}/samtools-{{ samtools_version }}.tar.bz2/download
    fn: samtools-{{ samtools_version }}.tar.bz2
    folder: samtools
    sha256: {{ samtools_sha256 }}

  - git_url: https://github.com/wtsi-npg/npg_qc_utils.git
    git_rev: {{ version }}
    folder: npg_qc_utils

requirements:
  build:
    - gcc_npg >=7.3
    - htslib =={{ htslib_version }}
    - zlib

  run:
    - htslib =={{ htslib_version }}
    - zlib

test:
  commands:
    - ${PREFIX}/bin/fastq_summ -h
    - test -e ${PREFIX}/bin/fastqcheck
    - test -e ${PREFIX}/bin/norm_fit
