{% set version = "2018_U4" %}
{% set sha256 = "d5604a04787c8a037d4944eeb89792e7c45f6a83c141b20df7ee89c2fb012ed1" %}

package:
  name: tbb
  version: "{{ version }}"

about:
  home: https://www.threadingbuildingblocks.org
  license: Apache 2.0
  summary: "Threading Building Blocks (Intel TBB)"

build:
  number: 0

  rpaths:
    - lib
    - lib64

source:
  url: https://github.com/01org/tbb/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

requirements:
  build:
    - gcc_npg <4.8

test:
  commands:
    - test -f ${PREFIX}/include/tbb/tbb.h
    - test -f ${PREFIX}/lib/libtbb.so
