{% set version = "0.5.10_mt_fixes.2" %}

package:
  name: bwa-aligner
  version: "{{ version }}"

about:
  home: https://github.com/lh3/bwa
  license: GPLv3
  summary: Burrows-Wheeler Aligner for short-read alignment.

build:
  number: 0

source:
  - git_url: https://github.com/wtsi-npg/bwa.git
    git_rev: b8267d812d44036f5858baf3353fa5f4ceca06f8
    patches:
      - Makefile.patch

requirements:
  build:
    - zlib

  run:
    - zlib

test:
  commands:
    - test -x ${PREFIX}/bin/bwa
