{% set version = "3.10.2" %}
{% set short_version = "3.10" %}
{% set sha256 = "80d0faad4ab56de07aa21a7fc692c88c4ce6156d42b0579c6962004a70a3218b" %}

package:
  name: cmake
  version: "{{ version }}"

about:
  home: https://cmake.org/
  license: CMake
  summary: Cross Platform Makefile Generator.

source:
  url: https://cmake.org/files/v{{ short_version }}/cmake-{{ version }}.tar.gz
  fn: cmake-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

  rpaths:
    - lib64
    - lib

requirements:
  build:
    - gcc_npg >=7.3

  run:
    - libgcc_npg

test:
  commands:
    - cmake --help
