{% set version = "3.3.7" %}
{% set sha256 = "3b609b7feba5230e8f6dd8d245ddbefac324c5a6ae4186947670d9ac2cd25573" %}

package:
  name: fftw
  version: "{{ version }}"

about:
  home: http://fftw.org/
  license: GPLv3
  summary: "Library for computing the discrete Fourier transform (DFT)"

build:
  number: 0

source:
  url: http://fftw.org/fftw-{{ version }}.tar.gz
  fn: fftw-{{ version }}.tar.gz
  sha256: {{ sha256 }}

requirements:
  build:
    - gcc_npg >=7.3

test:
  commands:
    - test -f ${PREFIX}/include/fftw3.h
    - test -f ${PREFIX}/lib/libfftw3.a
    - test -f ${PREFIX}/lib/libfftw3f.a
