{% set version = "1.6.34" %}
{% set sha256 = "574623a4901a9969080ab4a2df9437026c8a87150dfd5c235e28c94b212964a7" %}

package:
  name: libpng
  version: "{{ version }}"

about:
  home: http://libpng.org/pub/png/libpng.html
  license: libpng
  summary: "The official PNG reference library."

source:
  url: https://download.sourceforge.net/libpng/libpng-{{ version }}.tar.gz
  fn: libpng-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - gcc_npg >=7.3
    - zlib

  run:
    - zlib

test:
  commands:
    - test -f ${PREFIX}/include/png.h
    - test -f ${PREFIX}/lib/libpng.a
    - test -h ${PREFIX}/lib/libpng.so
