{% set version = "2.0.10" %}
{% set sha256 = "d1cf83ed4ea3a9dfceaa6d9662ff645177090749881093051020bf42f9872b64" %}

package:
  name: mod_perl
  version: "{{ version }}"

about:
  home: https://apr.apache.org/
  license: ASL
  summary: Apache mod_perl

source:
  url: https://mirrors.ukfast.co.uk/sites/ftp.apache.org/perl/mod_perl-{{ version }}.tar.gz
  fn: mod_perl-{{ version }}.tar.gz
  sha256: {{ sha256 }}

requirements:
  build:
    - gcc_npg >=7.3
    - httpd
    - perl ==5.22.2
    - perl-local-lib

  run:
    - apr
    - apr-util
    - httpd
    - perl ==5.22.2
