{% set version = "4.2.7" %}

package:
  name: irods
  version: "{{ version }}"

about:
  home: https://irods.org
  license: BSD
  summary: "Open Source Data Management Software."

build:
  number: 5

source:
  - git_url: https://github.com/irods/irods.git
    git_rev: "{{ version }}"
    patches:
      - irods.patch
    folder: irods
  - git_url: https://github.com/irods/irods_client_icommands.git
    git_rev: "{{ version }}"
    patches:
      - icommands.patch
    folder: irods_client_icommands

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - clang==8.0.1
    - clangxx==8.0.1
    - make
  host:
    - libssl-dev
    - cppzmq
    - libarchive
    - avrocpp
    - boost-cpp>=1.73.0
    - zeromq
    - libpam
    - unixodbc
    - jansson
    - catch2
    - krb5
  run:
    - libssl
    - cppzmq
    - libarchive
    - avrocpp
    - boost-cpp>=1.73.0
    - zeromq
    - krb5

outputs:
  - name: irods-runtime
    version: {{ version }}
    requirements:
      host:
        - libssl-dev
      run:
        - libssl
        - boost-cpp>=1.73.0
        - avrocpp
        - jansson
        - zeromq
        - krb5
    files:
      - lib/irods/plugins
      - lib/libirods_client.so
      - lib/libirods_client.so.4.2.7
      - lib/libirods_common.so
      - lib/libirods_common.so.4.2.7
      - lib/libirods_plugin_dependencies.so
      - lib/libirods_plugin_dependencies.so.4.2.7
      - lib/libirods_server.so
      - lib/libirods_server.so.4.2.7

  - name: irods-dev
    version: {{ version }}
    requirements:
      run:
        - {{ pin_subpackage("irods-runtime", exact=True) }}
    files:
      - include/irods
      - lib/irods/externals
      - lib/libirods_client_api.a
      - lib/libirods_client_plugins.a
      - lib/libirods_client_api_table.a
      - lib/libirods_client_core.a
      - lib/libirods_client.a
      - lib/libRodsAPIs.a
      - lib/libirods_server.a
      - share/irods

  - name: irods-icommands
    version: {{ version }}
    requirements:
      run:
        - {{ pin_subpackage("irods-runtime", exact=True) }}
        - libssl
        - boost-cpp>=1.73.0
        - avrocpp
        - jansson
        - zeromq
    files:
      - bin/iadmin
      - bin/ibun
      - bin/ichksum
      - bin/ichmod
      - bin/icp
      - bin/idbug
      - bin/ienv
      - bin/ierror
      - bin/iexecmd
      - bin/iexit
      - bin/ifsck
      - bin/iget
      - bin/igroupadmin
      - bin/ihelp
      - bin/iinit
      - bin/ils
      - bin/ilsresc
      - bin/imcoll
      - bin/imeta
      - bin/imiscsvrinfo
      - bin/imkdir
      - bin/imv
      - bin/ipasswd
      - bin/iphybun
      - bin/iphymv
      - bin/ips
      - bin/iput
      - bin/ipwd
      - bin/iqdel
      - bin/iqmod
      - bin/iqmod
      - bin/iqstat
      - bin/iquest
      - bin/iquota
      - bin/irepl
      - bin/irm
      - bin/irmtrash
      - bin/irsync
      - bin/irule
      - bin/iscan
      - bin/isysmeta
      - bin/iticket
      - bin/itrim
      - bin/iuserinfo
      - bin/ixmsg
      - bin/izonereport

    test:
      commands:
        - ienv
